USE [master]
GO
/****** Object:  Database [prueba2]    Script Date: 01/11/2021 21:37:43 ******/
CREATE DATABASE [prueba2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'prueba2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\prueba2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'prueba2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\prueba2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [prueba2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [prueba2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [prueba2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [prueba2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [prueba2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [prueba2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [prueba2] SET ARITHABORT OFF 
GO
ALTER DATABASE [prueba2] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [prueba2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [prueba2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [prueba2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [prueba2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [prueba2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [prueba2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [prueba2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [prueba2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [prueba2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [prueba2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [prueba2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [prueba2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [prueba2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [prueba2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [prueba2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [prueba2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [prueba2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [prueba2] SET  MULTI_USER 
GO
ALTER DATABASE [prueba2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [prueba2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [prueba2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [prueba2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [prueba2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [prueba2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [prueba2] SET QUERY_STORE = OFF
GO
ALTER AUTHORIZATION ON DATABASE::[prueba2] TO [sa]
GO
USE [prueba2]
GO
/****** Object:  Table [dbo].[usuarios]    Script Date: 01/11/2021 21:37:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](40) NOT NULL,
	[Correo] [varchar](40) NOT NULL,
	[Telefono] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[usuarios] TO  SCHEMA OWNER 
GO
/****** Object:  Table [dbo].[usuarios2]    Script Date: 01/11/2021 21:37:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[usuarios2](
	[id] [int] NOT NULL,
	[nombre] [varchar](50) NOT NULL,
	[correo] [varchar](50) NULL,
	[telefono] [int] NULL,
 CONSTRAINT [PK_usuarios2] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER AUTHORIZATION ON [dbo].[usuarios2] TO  SCHEMA OWNER 
GO
SET IDENTITY_INSERT [dbo].[usuarios] ON 
GO
INSERT [dbo].[usuarios] ([Id], [Nombre], [Correo], [Telefono]) VALUES (1, N'edu', N'tec', 2021)
GO
INSERT [dbo].[usuarios] ([Id], [Nombre], [Correo], [Telefono]) VALUES (2, N'Fabian', N'fabian@gmail', 63686182)
GO
INSERT [dbo].[usuarios] ([Id], [Nombre], [Correo], [Telefono]) VALUES (3, N'usuarioprueba', N'prueba@gmail', 123456)
GO
INSERT [dbo].[usuarios] ([Id], [Nombre], [Correo], [Telefono]) VALUES (4, N'pruebaweb', N'web@gmail', 4321)
GO
SET IDENTITY_INSERT [dbo].[usuarios] OFF
GO
USE [master]
GO
ALTER DATABASE [prueba2] SET  READ_WRITE 
GO
